// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOYDd88RQ9j4w70NBLTMqeatMSJjpnts',
    appId: '1:730017097749:web:935fd63d7f91bf5ca5861c',
    messagingSenderId: '730017097749',
    projectId: 'howfar-chat',
    authDomain: 'howfar-chat.firebaseapp.com',
    storageBucket: 'howfar-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0d6Uk0sKTnLtGuGmCGeMlCSafYzn2rFw',
    appId: '1:730017097749:android:441d13d7591aae93a5861c',
    messagingSenderId: '730017097749',
    projectId: 'howfar-chat',
    storageBucket: 'howfar-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJXD0jhQTQppiX1577zs1fLlklvkRAsuo',
    appId: '1:730017097749:ios:9730de4e132664dca5861c',
    messagingSenderId: '730017097749',
    projectId: 'howfar-chat',
    storageBucket: 'howfar-chat.appspot.com',
    iosClientId: '730017097749-7p774ogm5b6vsg9s5afk5n2cv773910i.apps.googleusercontent.com',
    iosBundleId: 'com.example.howfarchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJXD0jhQTQppiX1577zs1fLlklvkRAsuo',
    appId: '1:730017097749:ios:9730de4e132664dca5861c',
    messagingSenderId: '730017097749',
    projectId: 'howfar-chat',
    storageBucket: 'howfar-chat.appspot.com',
    iosClientId: '730017097749-7p774ogm5b6vsg9s5afk5n2cv773910i.apps.googleusercontent.com',
    iosBundleId: 'com.example.howfarchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOYDd88RQ9j4w70NBLTMqeatMSJjpnts',
    appId: '1:730017097749:web:be5b4fee563ce88ba5861c',
    messagingSenderId: '730017097749',
    projectId: 'howfar-chat',
    authDomain: 'howfar-chat.firebaseapp.com',
    storageBucket: 'howfar-chat.appspot.com',
  );
}
